### ISSUE TITLE
tape-run does not work on travis ci

### ISSUE THREAD

**Issue by lakenen** [juliangruber/tape-run#5] opened 2015-01-27 07:59 UTC
When trying to run my tests on travis ci, I keep getting this error about firefox, even though I request `phantom` as the browser. My tests run just fine locally.

```
browserify test/*.js | ./node_modules/.bin/tape-run --browser phantom

firefox --no-remote -CreateProfile browser-launcher-6a189183 exited with code 1: Error: no display specified
```

See the full log here: https://travis-ci.org/lakenen/wrap-range-text/builds/48451040

Any idea what's going on here? Is tape-run not supported on travis ci? FWIW I get a similar error when using testling (which also runs fine locally). I imagine it could be a problem with browser-launcher, but I don't know enough about that project to know for sure.

**Comment by juliangruber** [comment] 2015-01-27 13:53
hhmmm @substack do you have any experience running browser-launcher on travis?

**Comment by tomekwi** [comment] 2015-02-06 11:56
@juliangruber Travis has issued a guide about [headless browser testing](http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-PhantomJS).

It looks as if they have phantom exposed as `phantomjs` in the PATH. How about a CLI option like `--browser-binary` which would override browser-launcher and spawn the command instead? Just an idea.

**Comment by juliangruber** [comment] 2015-02-06 14:18
that would work but isn't a good solution, browser-launcher should support that

**Comment by tomekwi** [comment] 2015-02-07 01:10
Well, what when someone installs their browser in a non-standard location, or sandboxed somehow, or whatever-else-the-reason-browser-launcher-wont-work? I don't know the inner workings of browser-launcher, but I doubt it can cover every case and every browser in the world.

Just my 2c to keep the discussion going :)

**Comment by binarykitchen** [comment] 2015-02-07 02:22
Hmmm, I am having the same issue here as @lakenen has experienced and would welcome a solution that will work with Travis.

Why can't we introduce a new option to pass on the phantomjs executable? Like that we can pass on the phantomjs PATH from Travis.

**Comment by juliangruber** [comment] 2015-02-07 06:47
can you confirm that the name of the binary is the problem?

**Comment by tomekwi** [comment] 2015-02-07 10:16
I can only confirm that the error message I'm seeing looks exactly like that of @lakenen. It looks as if browser-launcher can't detect PhantomJS and tries to fall back to Firefox – which fails because it can't display its window.

For reference: https://travis-ci.org/tomekwi/mithril-n/builds/49787722

**Comment by juliangruber** [comment] 2015-02-07 11:02
looks like browser-launcher expects the bin to be called `phantom`: https://github.com/substack/browser-launcher/blob/master/lib/detect.js#L26

**Comment by juliangruber** [comment] 2015-02-07 11:03
correction, it's phantomjs: https://github.com/substack/browser-launcher/blob/master/lib/detect.js#L59

**Comment by juliangruber** [comment] 2015-02-07 11:04
can someone do `phantomjs --version` on a travis box?

**Comment by tomekwi** [comment] 2015-02-07 11:19
https://travis-ci.org/tomekwi/phantom-test/builds/49847713

**Comment by juliangruber** [comment] 2015-02-09 17:08
i tried to ssh into a travis box but either i didn't find that feature or it never existed. looks like we could use one of their vagrant boxes to evaluate this

**Comment by tomekwi** [comment] 2015-03-09 23:33
@juliangruber looks like Travis has deprecated their Vagrant boxes: https://github.com/travis-ci/travis-boxes .

As for browser-launcher, I've tried to [make it list available browsers and their paths](https://github.com/tomekwi/phantom-test/blob/master/launcher.js). It errors at that point and quits: https://travis-ci.org/tomekwi/phantom-test/builds/53730516 .

**Comment by tomekwi** [comment] 2015-03-09 23:44
So yeah, it is a bug in browser-launcher after all. The problem is, [it doesn't seem](https://github.com/substack/browser-launcher/issues) [to be actively maintained](https://github.com/substack/browser-launcher/pulls) anymore.

There is a fork called [browser-launcher2](https://github.com/benderjs/browser-launcher2). No idea how reliable it is – but at least there are signs of life in the repo :)

**Comment by juliangruber** [comment] 2015-03-24 09:05
yisssss [![build status](https://secure.travis-ci.org/juliangruber/tape-run.svg)](http://travis-ci.org/juliangruber/tape-run)

fixed by https://github.com/juliangruber/browser-run/commit/e7cb6f533c55e5d74a3e633f9369d2d16d9fd798

**Comment by tomekwi** [comment] 2015-03-24 10:35
Great, thanks man! :beers: 

Can't wait to test it out – I hope I'll manage today.

**Comment by lakenen** [comment] 2015-03-24 21:31
Thanks! Nice work!

**Comment by tomekwi** [comment] 2015-03-25 21:56
Works like a charm. Thanks again!

**Comment by daliwali** [comment] 2015-06-22 21:46
Issue janitor here. If this issue is resolved, I guess it can be closed. Or does it still not work on Travis CI?

**Comment by tomekwi** [comment] 2015-06-22 22:08
I’ve had no problems

**Comment by juliangruber** [comment] 2015-06-22 22:36
yaaaaaaay

**Closed** 2015-06-22 22:36 UTC

**Comment by tomekwi** [comment] 2015-06-23 06:39
:+1: :+1: :+1:
